### ISSUE TITLE
Not running on devices running lower than lollipop

### ISSUE THREAD

**Issue by smanne** [chrisjenx/Calligraphy#136]
I am able to run calligraphy ver 2.0.1 on lollipop device, if I try to run it on lower version device (kitkat) I am getting following issue

02-16 16:19:23.541    3053-3053/com.tabtor.student E/dalvikvm﹕ Could not find class 'uk.co.chrisjenx.calligraphy.CalligraphyFactory', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.<init>
02-16 16:19:23.541    3053-3053/com.tabtor.student E/dalvikvm﹕ Could not find class 'uk.co.chrisjenx.calligraphy.CalligraphyFactory', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.<init>
02-16 16:19:23.541    3053-3053/com.tabtor.student E/dalvikvm﹕ Could not find class 'uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setUpLayoutFactories
02-16 16:19:23.541    3053-3053/com.tabtor.student E/dalvikvm﹕ Could not find class 'uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setUpLayoutFactories
02-16 16:19:23.541    3053-3053/com.tabtor.student E/dalvikvm﹕ Could not find class 'uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setFactory
02-16 16:19:23.541    3053-3053/com.tabtor.student E/dalvikvm﹕ Could not find class 'uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setFactory2
02-16 16:19:23.541    3053-3053/com.tabtor.student E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: uk.co.chrisjenx.calligraphy.CalligraphyFactory
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.<init>(CalligraphyLayoutInflater.java:43)
            at uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper.getSystemService(CalligraphyContextWrapper.java:111)
            at android.view.LayoutInflater.from(LayoutInflater.java:210)
            at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:113)
            at android.app.Activity.getSystemService(Activity.java:4473)
            at android.view.LayoutInflater.from(LayoutInflater.java:210)
            at com.android.internal.policy.impl.PhoneWindow.<init>(PhoneWindow.java:218)
            at com.android.internal.policy.impl.Policy.makeNewWindow(Policy.java:63)
            at com.android.internal.policy.PolicyManager.makeNewWindow(PolicyManager.java:59)
            at android.app.Activity.attach(Activity.java:5063)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2129)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by chrisjenx** [comment]
That is saying it can't find `CalligraphyFactory`. 
Are you targeting the latest sdk version?
You are going to have to give me a better stack trace. Have you only tried on two devices? Have you cleaned you build then recompiled? Are you using proguard (not that it strips out Calligraphy anyway).

**Comment by smanne** [comment]
I tried it in android lollipop device same build worked and when I trying on android 4.4 emulator or samsung galaxy alpha device or 4.2 genymotion emulator I am getting following error. 

targetSdkVersion 21, 

If its proguard related then I am thinking it wont run on lollipop device also.

Here is how I used Calligraphy
added following line in build.gradle dependency
```
compile 'uk.co.chrisjenx:calligraphy:2.0.1'
```
Added following lines in MyApplication
```
CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                        .setDefaultFontPath("fonts/avenir-light.ttf")
                        .setFontAttrId(R.attr.fontPath)
                        .build()
        );
```
Added following lines in root activity which all other activies extend
```
@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }
```

**Comment by smanne** [comment]
I added following code in MyApplication class also which I removed 
```
@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }
```

Now I am getting this exception now (In both cases its working in lollipop) 
```
02-16 17:53:07.305    3512-3512/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: uk.co.chrisjenx.calligraphy.R$attr
            at uk.co.chrisjenx.calligraphy.CalligraphyConfig$Builder.<init>(CalligraphyConfig.java:108)
            at com.tabtor.student.TabtorStudentApplication.onCreate(TabtorStudentApplication.java:29)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
            at android.app.ActivityThread.access$1300(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by chrisjenx** [comment]
Add @aar to your dependency to make sure it uses the aar.

**Comment by chrisjenx** [comment]
Hang on I see instrumentation in the stack trace

**Comment by smanne** [comment]
I found the issue, It is with multidex, but after enabling multidex font overriding is not working even in lollipop also. Can you please point me correct setting for using calligraphy with multidex.

**Comment by hateum** [comment]
How many libs are you using on your code ? are you using less than 65K function ? this is the limit in dex file.
So try using multiDex.

**Comment by chrisjenx** [comment]
Oh dang. Never had to use multidex! I would seriously review how many libs
you use or at least use proguard!

**Comment by chrisjenx** [comment]
@hateum @smanne I talked to some Androiders on Wednesday. Seem that there is quite a bug with Multidex and libs. Where the dex is not loaded fully pre Lollipop. It is meant to have been fixed in the very latest build tools and multidex, I would check everything is up to date.

**Comment by chrisjenx** [comment]
This should've been fixed in build tools 21.1.1, Please reopen if you still have issues, Although I'm 99% sure this is a build script issue.

**Comment by irfanelahi** [comment]
Hi 
I have been struggling with same issue. I am new to Android Studio, interesting thing is it worked for a week or so, I have been doing changes in my project. Then All of a sudden, it messed up. Don't remember what I changed that caused me  this issue.

04-29 11:53:33.980  16668-16668/com.xxx.xxx E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: uk.co.chrisjenx.calligraphy.R$attr
            at uk.co.chrisjenx.calligraphy.CalligraphyConfig$Builder.<init>(CalligraphyConfig.java:108)
            at com.xxx.xxx..ApplicationController.onCreate(ApplicationController.java:62)

Can you guys please tell me the issue, looking for help. Have been struggling with it from days now. 
Note: Same code works fine on Android Lollipop OS.

**Comment by chrisjenx** [comment]
@irfanelahi are you using Multidex?

**Comment by Arash-gm** [comment]
@chrisjenx : i have exactly same issue chris , i've faced some issues when i've added support library v13 , so i had to enable multidex support , and after that i'see error : 

    java.lang.NoClassDefFoundError: uk.co.chrisjenx.calligraphy.R$attr

do you know how can i fix this?

**Comment by chrisjenx** [comment]
Make sure you are using the latest build tools etc... The multidex issues
were fixed back in a build tools point release a while ago.

**Comment by Arash-gm** [comment]
@chrisjenx : i've updated android studio to 1.2.1.1 but the problem doesn't solve

**Comment by chrisjenx** [comment]
I can't help you then. Maybe one of the other guys here can help. I've
never used multidex.

**Comment by sawcioo** [comment]
@Arash-gm are you sure that you Application class extends MultiDexApplication?

**Comment by Arash-gm** [comment]
@sawcioo : yes i've found that the error was for extending MultiDexApplication , but found another solution to not using MultiDex anymore. ;)

**Comment by HugoMatilla** [comment]
Configuring correctly multidex fixed the error in my code.

When using Multidex  do not forget to add this to your main application:

```java
@Override
protected void attachBaseContext(Context base) {
  super.attachBaseContext(base);
  MultiDex.install(this);
}
```
and this in the Manifest
```xml
android {
...
         defaultConfig {
             minSdkVersion 14 //lower than 14 doesn't support multidex
             targetSdkVersion 21

             // Enabling multidex support.
             multiDexEnabled true
         }
}

dependencies {
    compile 'com.android.support:multidex:1.0.1'
}
```

links : https://developer.android.com/reference/android/support/multidex/MultiDexApplication.html
and: http://stackoverflow.com/a/27284064/749393

**Comment by nvinayshetty** [comment]
@HugoMatilla :Thanks a lot man that solution worked for me,I think you are right the problem is with incorrectly configured multidex....I was struggling with that problem from two days..Thanks a lot:) you saved my day

**Comment by qbig** [comment]
+1 for the multidex fix! It worked for me as well

**Comment by Cutta** [comment]
@HugoMatilla  Thanks a lot. You saved my day.

**Comment by ericbatemandev** [comment]
@HugoMatilla Thank you so much for the multidex fix. Saved me a TON of time!

**Comment by alpbak** [comment]
@HugoMatilla Thanks for the multidex tip. I owe you a beer :)

**Comment by dineshhirani** [comment]
It helped me . thanks a lot @HugoMatilla

**Comment by OssamaCoder** [comment]
Thank you so much @HugoMatilla

**Comment by victorolowe** [comment]
Anyone still having this issue:
In your Application class, instead of extending Application, extends MultiDexApplication like so:
`class MyApplication extends MultiDexApplication`

**Comment by chrisjenx** [comment]
I never extend multidex application, I call multidex.install manually.

The key thing, make sure you are using the latest build tools, and multidex
1.0.1.

**Comment by HITESHGOEL08** [comment]
I am latest Android Studio 2.3.3. I am using Facebook SDK with Firebase SDK and Adobe Creative SDK, due to which iI have to Multidex application which enables Multidex dependency.

I am trying to install app on lollipop 5.1 but it shows 

com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/iid/zzc.class


I even tried with other OS when using API below 22 it shows this error but when using API 23 above its installed and is running perfectly.

how to solve this problem...


My gradle file is 

      apply plugin: 'com.android.application'
      apply plugin: 'me.tatarka.retrolambda'
        android {
                  compileSdkVersion 25
                 buildToolsVersion '25.0.3'
                defaultConfig {
                 applicationId "com.practice.android.moments"
                 minSdkVersion 18
                 targetSdkVersion 25
                  versionCode 1
                versionName "1.0"
           
                multiDexEnabled true
        
                testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    
                manifestPlaceholders = [appPackageName: "${applicationId}"]
               }

               buildTypes {
                       release {
                           minifyEnabled false
                   proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                    }
                      }

                 dexOptions {
                           jumboMode true
                        }
               compileOptions {
                                 sourceCompatibility JavaVersion.VERSION_1_8
                                 targetCompatibility JavaVersion.VERSION_1_8
                                         }
 
                     /* 3)(Creative SDK) Exclude duplicate licenses */
                packagingOptions {
                           exclude 'META-INF/LICENSE.txt'
                           exclude 'META-INF/LICENSE'
                           exclude 'META-INF/LICENSE-FIREBASE.txt'
                           exclude 'META-INF/NOTICE'
                           exclude 'META-INF/NOTICE.txt'
                           exclude 'META-INF/DEPENDENCIES'
                           pickFirst 'AndroidManifest.xml'
                       }
                       }

                       repositories {
                                              mavenCentral()
                                              }
                       dependencies {

                       compile fileTree(include: ['*.jar'], dir: 'libs')
                       androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
                           exclude group: 'com.android.support', module: 'support-annotations'
                       })
                       compile 'com.android.support:recyclerview-v7:25.3.1'
                       compile 'com.android.support:appcompat-v7:25.3.1'
                       compile 'com.android.support.constraint:constraint-layout:1.0.2'
                       compile 'com.android.support:cardview-v7:25.3.1'
                       compile 'com.google.android.gms:play-services-auth:11.0.1'
                       compile 'com.google.firebase:firebase-core:11.0.1'
                       compile 'com.google.firebase:firebase-messaging:11.0.1'
                       compile 'com.google.firebase:firebase-auth:11.0.1'
                       compile 'com.google.firebase:firebase-database:11.0.1'
                       compile 'com.google.firebase:firebase-storage:11.0.1'
                       compile 'com.google.firebase:firebase-ads:11.0.1'
                       compile 'com.google.firebase:firebase-invites:11.0.1'
                       compile 'com.google.firebase:firebase-appindexing:11.0.1'
                       compile 'com.google.firebase:firebase-crash:11.0.1'
                     
                       compile 'com.facebook.android:facebook-android-sdk:[4,5)'
                       compile 'com.android.support:support-v4:25.3.1'
                       compile 'com.android.support:design:25.3.1'
                       compile 'de.hdodenhof:circleimageview:2.1.0'
                       compile 'com.android.support:multidex:1.0.1'

                       compile 'com.adobe.creativesdk.foundation:auth:0.9.1251'
                       compile 'com.adobe.creativesdk:image:4.8.4'
                       compile 'com.localytics.android:library:3.8.0'

                       testCompile 'junit:junit:4.12'}

                configurations.all {
                       resolutionStrategy.force 'com.google.code.findbugs:jsr305:3.0.1'}
                       
                       apply plugin: 'com.google.gms.google-services'

**Comment by chrisjenx** [comment]
And your raising this issue here why?
