### ISSUE TITLE
Toolbar title is moving when swapping fragments

### ISSUE THREAD

**Issue by mzgreen** [chrisjenx/Calligraphy#304]
Hi!

I have one activity and two fragments. Each fragment has it's own `Toolbar` with different title. When I swap fragments (using `transaction.replace`) then the title is moving/jumping. In 2.1.0 it's a little better. Movement is a lot less visible but it's still there.
Here is a sample project that reproduces this issue: https://drive.google.com/open?id=0B4aF0Bxe-ecnRjBCaEdIMzMxYVU

It's not using any custom fonts, wrapping `Context` in `attachBaseContext` is enough to reproduce this issue.

**Comment by mzgreen** [comment]
Workaround for this would be to move the `Toolbar` to the Activity. When only text is changing on the already inflated `Toolbar` this bug is not present.

**Comment by chrisjenx** [comment]
@mzgreen have you tried the latest support lib, (24.0.0) some users have reported the Jumping around has been fixed.

**Comment by mzgreen** [comment]
Yes, the sample code actually uses 24.0.0.

**Comment by Nik27** [comment]
It worked for me: `toolbar.setSubtitle(null);`

**Comment by mzgreen** [comment]
@Nik27 where exactly did you put that?
@chrisjenx If setting subtitle to null really helps, do you have an idea why?

**Comment by chrisjenx** [comment]
Setting null probably instantiates the subTitle TextView so it's laid out
correctly. I'll see if I can do something similar

**Comment by Nik27** [comment]
@mzgreen 
[https://github.com/Nik27/CalligraphyToolbarBug](https://github.com/Nik27/CalligraphyToolbarBug)

**Comment by Nik27** [comment]
@chrisjenx 
I think this is due to `toolbar.setSubtitle(BLANK);` in `CalligraphyFactory.ToolbarLayoutListener`

**Comment by TheIronMarx** [comment]
This seems to only periodically occur in my case. Maybe 80% of the time instead of a font change being applied to my `Toolbar`'s title, it will layout an empty subtitle and make no changes to the title itself (aside from pushing it upwards to make room for the subtitle. Oddly, this doesn't occur with my other fragments, just the first one to be inflated on the first activity. 

Frustratingly, I'm doing nothing with subtitles at all in my application.

**Comment by TheIronMarx** [comment]
Maybe I've narrowed it down. It seems when the first toolbar is being rendered, the bug occurs, but if the app is still in memory or I'm going to another fragment, the title rendering works. Closing the app and reopening works correctly, but closing, swiping from recent apps, then reopening causes the bug.

**Comment by TheIronMarx** [comment]
As for @Nik27's suggestion about `toolbar.setSubtitle(null)`, this doesn't seem reliable. When I tried doing that during the `Toolbar`'s construction, the subtitle with one space, `ToolbarLayoutListener.BLANK`, still appeared. However when I did it in the corresponding Fragment's `onViewCreated`, the `BLANK` subtitle was gone. With both of these cases, the custom font is never set, so it still isn't a complete solution.

The `toolbar.setSubtitle(null)` call at different times had different results, but both happen after the attaching `Activity`'s `attachBaseContext()` has been called. So perhaps there's a race condition occurring?

**Comment by thuytrinh** [comment]
This happened quite randomly. Upgrading to support lib v24.x wouldn't resolve the issue. I think I'm gonna put the `Toolbar` with no title inside a `FrameLayout`, then put a `TextView` with left margin on top of the bar. Kinda fake toolbar title anw but that'd at least likely make the issue away.

**Comment by Bombo** [comment]
@chrisjenx 
I don't know if this is actually adding to this issue, but here's what I've found:

First of all I also have the `Toolbar` in my `Fragment` class and I'm setting the `Activity`'s SupportActionBar in `onCreateView` of each fragment.
When my activity is first loaded, the title does not have the custom font but the regular one and also displays an empty subtitle (I don't populate the subtitle).
This is because as though the `CalligraphyFactory.ToolbarLayoutListener` constructor is called (setting the subtitle to `BLANK` as noted by @Nik27) the `onGlobalLayout` method exits prematurely, because the `WeakReference` of the `Toolbar` instance returns `null` at this point. Subsequently the toolbar renders perfectly fine.

So I don't have a solution, yet, but wanted to add my findings to this. I will take another look on Monday.

Thanks for this nice library, btw. Really makes my life easier! :)

**Comment by chrisjenx** [comment]
Wondering if this fixes it #327

**Comment by Bombo** [comment]
Yes, it appears to, actually. In addition to no "empty" subtitle showing up anymore, the custom font seems to be applied consistently, now. I was counting on the first part being fixed by this, but have to say that I'm a little bit confused about how this fixes the second one. ;)

Although I have to admit that I have troubles reproducing the issues at all with the release version right now. Last week I got the behavior pretty constantly.

**Comment by gjsalot** [comment]
@chrisjenx @Bombo 
#327 does seem to fix the "empty" subtitle issue. However, it does not seem to fix the custom font not being applied consistently.

**Comment by mzgreen** [comment]
This still doesn't work for me. I'm on support `25.1.0`.
Everything seems to be ok, but if I start switching between 2 fragments back and forth then after couple of trials toolbar stays aligned to top (invisible subtitle?) with Roboto instead of custom font.
Is there any known workaround? Maybe wrapping `TextView` inside `Toolbar` would help?

**Comment by chrisjenx** [comment]
Could do a custom toolbar. But there is a pull request that might fix this.

**Comment by mzgreen** [comment]
What do you mean by custom Toolbar? Put TextView inside and not use toolbar's title property or completely custom view instead on toolbar?

**Comment by chrisjenx** [comment]
Correct
